#!/usr/bin/env python3
"""Flatten assets/css/main.css @import pipeline into a single stylesheet.

Development keeps the modular @import graph (cascade contract documented in
main.css). Production/CDN deploys should serve the flattened file to avoid
the browser blocking on ~25 serial @import round-trips.

Usage:
  python3 tools/flatten_css.py            # writes assets/css/dist/main.flat.css
  python3 tools/flatten_css.py --check    # verify flatten matches current graph

Does not modify the modular sources — safe alongside parity suites.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSS = ROOT / "assets" / "css"
ENTRY = CSS / "main.css"
OUT = CSS / "dist" / "main.flat.css"

IMPORT_RE = re.compile(r"@import\s+url\(['\"]([^'\"]+)['\"]\)\s*;")


def strip_comments(css: str) -> str:
    return re.sub(r"/\*.*?\*/", "", css, flags=re.S)


def flatten(path: Path, seen: set[Path] | None = None) -> str:
    seen = seen or set()
    rp = path.resolve()
    if rp in seen:
        raise SystemExit(f"Circular @import: {rp}")
    seen.add(rp)
    css = path.read_text(encoding="utf-8")
    parts: list[str] = []
    last = 0
    for m in IMPORT_RE.finditer(css):
        parts.append(css[last : m.start()])
        target = (path.parent / m.group(1)).resolve()
        if not target.exists():
            raise SystemExit(f"Missing import: {target} (from {path})")
        # Preserve a banner so reviewers know which module is which.
        parts.append(f"/* --- {target.relative_to(CSS)} --- */\n")
        parts.append(flatten(target, seen))
        parts.append("\n")
        last = m.end()
    parts.append(css[last:])
    return "".join(parts)


def main() -> int:
    body = flatten(ENTRY)
    header = (
        "/* GENERATED by tools/flatten_css.py — do not edit.\n"
        " * Source of truth: assets/css/main.css @import graph.\n"
        " * Serve this file in production to eliminate @import waterfalls.\n"
        " */\n\n"
    )
    output = header + body
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != output:
            print("OUT OF DATE — run: python3 tools/flatten_css.py", file=sys.stderr)
            return 1
        print(f"OK {OUT.relative_to(ROOT)} up to date ({len(output)} bytes)")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(output, encoding="utf-8")
    # Sanity: flattened must contain every original @import target's last selector marker
    n_imports = len(IMPORT_RE.findall(ENTRY.read_text()))
    print(f"Wrote {OUT.relative_to(ROOT)} ({len(output)} bytes) from {n_imports} top-level graph")
    # Count nested imports resolved
    nested = output.count("/* --- ")
    print(f"Modules inlined: {nested}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
